# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-01 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_schedule', '0004_auto_20180630_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='override_rowspan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
