# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-05 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_schedule', '0005_slot_override_rowspan'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='title_override',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
