# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-03 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_schedule', '0007_presentation_feedback_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='feedback_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
