# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-10 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_sponsorship', '0003_auto_20170813_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorlevel',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Available?'),
        ),
    ]
