# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-23 06:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_sponsorship', '0004_sponsorlevel_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualSponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sponsor Name')),
                ('display_name', models.CharField(blank=True, max_length=100, verbose_name='Display Name')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Anonymous?')),
                ('amount', models.IntegerField(default=50, verbose_name='Donation Amount')),
                ('added', models.DateTimeField(default=datetime.datetime.now, verbose_name='added')),
            ],
            options={
                'ordering': ['-amount', 'added'],
            },
        ),
    ]
